name: Hello World M

on:
  workflow_dispatch: #manually trigger workflow

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello World" from an inline bash script in a workflow

  say-hello-inline-python:
    runs-on: ubuntu-24.04
    steps:
      - run: print("Hello World from an inline python script in a Github action Workflow")
        shell: python

  say-hello-action:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/hello-world-javascript-action
        with:
          who-to-greet: "From an action in the Github marketplace"
